### ISSUE TITLE
formly fieldGroup

### ISSUE THREAD

**Issue by jaideepdas** [formly-js/vue-formly-bootstrap#11]
I am trying to use field group option of formly it keeps getting error.
```
{
          className: 'panel-body',
          fieldGroup: [{
            wrapper: '<div class="col-md-12"></div>',
            key: 'isDisabled1',
            type: 'list',
            options: [{
              label: 'Yes',
              value: true
            }, {
              label: 'No',
              value: false
            }],
            templateOptions: {
              atts: {},
              inputType: 'radio',
              label: 'Is Disabled'
            }
          }, {
            wrapper: '<div class="col-md-12"></div>',
            key: '_sort1',
            type: 'input',
            templateOptions: {
              atts: {
                type: 'number',
                step: '0.1'
              },
              label: 'Sort Order'
            }
          }]
        }
```
Error
``` Unknown custom element: <formly_undefined> - did you register the component correctly? For recursive components, make sure to provide the "name" option.```

Is this option not implemented? http://docs.angular-formly.com/v6.4.0/docs/field-groups

**Comment by matt-sanders** [comment]
Nope, it's not implemented, that's for Angular Formly, so there are quite a few differences. Be sure to refer to the specific docs for either Vue Formly or Vue Formly Bootstrap. See the section in the Vue Formly docs about [advanced layouts](https://matt-sanders.gitbooks.io/vue-formly/content/v/2.0/how_to_use/advanced_form_layouts.html)

**Comment by jaideepdas** [comment]
The URL shared was for reference. So is there a work around. Else will have
to do away with formly as it seems.

**Comment by matt-sanders** [comment]
Well, it depends on what you want to do. there is the `wrapper` option available to each field which could help you. Otherwise you could always use a fully custom layout. See [the first example here](https://matt-sanders.gitbooks.io/vue-formly/content/v/2.0/how_to_use/advanced_form_layouts.html) as it uses the wrapper option.

**Comment by jaideepdas** [comment]
Thanks will give that a try
