### ISSUE TITLE
Example of using onClick or any other event handler with templateOptions

### ISSUE THREAD

**Issue by champeng** [formly-js/vue-formly-bootstrap#12]
I am trying to attach a very simple click event handler for `list` form field, however, I didn't find any working example. When I try following syntax, it just fails to render:

<pre>
"templateOptions" : {
  "onClick": function() {
    console.log('clicked');
  }
}
</pre>

and when I try

<pre>
"templateOptions" : {
  "onClick": "handleClick()" // handleClick is a method in the controller
}
</pre>

it renders, but no click event handler is bounded to the form element.

**Comment by matt-sanders** [comment]
Hey @champeng 
Are you able to send through any more of your code, or you can send it privately if that's an issue, it seems to be working ok for me. I don't think it currently supports methods defined under methods, but I'll add support for that soon.

**Comment by champeng** [comment]
@matt-sanders Thanks for the response. However, it is not working for me and I have no idea why. I am not sure what all code should I send to you because either this snippet would suffice or I have to share the complete code base which unfortunately I can not do.

**Comment by matt-sanders** [comment]
well if you can't provide any more context, and I can't replicate the issue, there's not a whole lot I can do for you. Here's a few more things to try:
in this example:
```
"templateOptions" : {
  "onClick": "handleClick()" // handleClick is a method in the controller
}
```
you are calling `handleClick` incorrectly. by stating `"onClick": "handleClick()"` you are passing it a string, not a function. Try first to define `handleClick`:
```
function handleClick(){
   console.log('something');
}
```
then in your code: `onClick: handleClick` note that it is not `onClick: handleClick()` as that would be calling the function immediately, which we don't want.

When you say that "it just fails to render" I'll need more detail if you want me to help with that. Do you get any errors in the console? Do you get any errors in your build output? Can you provide the whole .vue file, including the template ( assuming you're using .vue files )? Are you using something like the [webpack](https://github.com/vuejs-templates/webpack) template or your own custom build pipeline?

There could be a thousand reasons for something to "just not render" so without more detail I would just be guessing.

**Comment by champeng** [comment]
Thanks @matt-sanders again for the response. Yes, I know without much context it is really difficult to help here. Please excuse my novice skills for vue. I am very new to vue. We are not using webpack or anything else it is just `nodemon server.js`.

By "it just fails to render", I meant I just get a blank page if I put a real function in the JSON. Visual Code itself complains about the syntax. In the actual code we are fetching the fields configuration via ajax call(I am not sure why) which seems to be the cause of the error. Actually, it is jQuery's $ajax method that is failing when parsing the JSON response which contains a function.

Thanks for the response and time @matt-sanders

**Comment by matt-sanders** [comment]
hmm, ok. that sounds like an interesting setup. This sounds to me more like an issue with how you are sending your code than an actual issue with Formly unfortunately. Maybe you're not encoding your JSON correctly? Although, it's not really JSON that you're sending if you're trying to send a function is it, it's JavaScript, which is probably why it's failing. Maybe you need to look into converting the function into a string and then doing something with `eval()` to turn it back into a javascript function before you add it to Formly. Or, define all your functions first and just send a reference to the function or something.

Either way, I think your issues are a bit out of scope with Formly sorry. But as a suggestion, this is what I would do:
 - make AJAX call for field definitions from the server
 - make sure the server is encoding everything into correct JSON. E.g. a JS function is not valid JSON, but maybe you could stringify the function?
 - when you receive the JSON, on the front-end, have a handler function, which takes the JSON and converts everything back into JavaScript. E.g. takes stringified functions and turns them into real functions with `eval()` or something of the sorts. Beware of the inherent dangers of `eval`
 - once you've finally converted everything, then pass the new data to Formly.

**Comment by champeng** [comment]
Thanks @matt-sanders. I can understand. I think stringify and eval would be the option for me.
