### ISSUE TITLE
v-mask

### ISSUE THREAD

**Issue by n0n3br** [formly-js/vue-formly-bootstrap#14]
i'm trying to create a custom field type with mask suport, but can't get to work right.
Maybe you could provide the default template for all the input types so I can achieve what I want more easily.

**Comment by matt-sanders** [comment]
All the fields are in https://github.com/formly-js/vue-formly-bootstrap/tree/master/src/fields
The baseField.js file contains some basic functionality that they all use, not that you're required to use it, but that does give some helpers.
