### ISSUE TITLE
'methods' property not provided?

### ISSUE THREAD

**Issue by dam0** [formly-js/vue-formly-bootstrap#3]
Usage example shows:
...,
 methods: {
      doSomething: function(){}
   }

Methods not shown as a property of vue-formly -  https://matt-sanders.gitbooks.io/vue-formly/content/v/2.0/how_to_use/properties_and_options.html

**Comment by matt-sanders** [comment]
Hey man, first of all sorry for the late reply!
That "methods" property that you referenced isn't actually part of Vue Formly, that's a Vue property. I've updated the usage example to make it clearer ( and I also noticed an error there too! ). So what's happening is that in that example you're creating a Vue instance. The `methods` property is part of Vue and that's got a function in it to execute when the form submits. You'll see now I've made it clearer by adding a form element with the submit method on it that is triggered ( by Vue ) when the form submits.

Hope that makes sense!
