### ISSUE TITLE
How to make checkbox and radio objects appear?

### ISSUE THREAD

**Issue by mikeerickson** [formly-js/vue-formly-bootstrap#5]
I am having an issue getting my checkbox (and surely radio) objects to appear.  My construct is as follows, is something missing?

```
...
  {
    key: 'married',
    type: 'list',
    templateOptions: {
      label: 'Married'
      inputType: 'checkbox',
      options: ['married'],
    }
  }
```

**Comment by matt-sanders** [comment]
So close! `options` should be outside of `templateOptions`
```js
...
  {
    key: 'married',
    type: 'list',
    options: ['married'],
    templateOptions: {
      label: 'Married'
      inputType: 'checkbox',
    }
  }
```

**Comment by mikeerickson** [comment]
Well I knew it was something simple :-)

**Comment by mikeerickson** [comment]
Wait a second... While I have you :-)

When the checkbox is displayed, it uses the `options` as the checkbox label instead of the `templateOptions.label` property

![image](https://cloud.githubusercontent.com/assets/183153/23674830/1ced71d0-032c-11e7-8871-b42225ee630d.png)

**Comment by mikeerickson** [comment]
I store the value in the database as `married` but want it to display as `Married`

And, further down the line, this project will need to be in Spanish (frontend) but actual values, etc. will be stored in english

**Comment by mikeerickson** [comment]
And, I presume that a `radio` object will be even more important?

Yup, as expected ... The storage values are accurate, but display values need to be different

![image](https://cloud.githubusercontent.com/assets/183153/23674947/87faf27c-032c-11e7-99f2-d59b769fd496.png)

**Comment by matt-sanders** [comment]
Yup, you can pass either an array of string values to options or an array of objects with a `value` and `label` property. `templateOptions.label` is for the actual field label. E.g. you may have something like this:
```js
...
{
   key: 'married',
   type: 'list',
   options: [
      { label: 'Casado', value: 'married' },
      { label: 'Solo', value: 'single' }
   ],
   templateOptions: {
      label: 'Casado?',
      inputType: 'radio'
   }
}
```

**Comment by mikeerickson** [comment]
Perfect :-)

One last question, and then I am off the races completing this form.   How does one go about adding additional attributes.   

I need to apply some additional classes for each item AND need to supply `id` and `name` properties.  Are these just extra `templateOptions`

**Comment by mikeerickson** [comment]
I see there is an item for `id` how about `name`?  And I found the property for `classes`  I guess I could just add `name` to the `attrs` property

**Comment by matt-sanders** [comment]
Yup sure are, you can use `atts`, `classes`, and `id`. The info for how to use each is in the vue formly bootstrap docs section in the readme

**Comment by matt-sanders** [comment]
https://github.com/formly-js/vue-formly-bootstrap#template-options

**Comment by matt-sanders** [comment]
classes takes an object with the class name and then true/false values. This is so that you can toggle the class as per Vue docs. The atts object takes a name/value key pair. Id is just a string

**Comment by rodrigoAbril** [comment]
Hi @matt-sanders , 

I am trying to group radios under a title but  templateOptions.label is missing from the list field
as @mikeerickson  commented on Mar 7 it only uses the options.label.

```
<template>
  <div class="checkbox formly-list" :id="to.id" :class="[to.wrapperClasses, {'has-error has-danger': hasError}]">

    <label v-for="option in field.options" :class="to.labelClasses">
      <input v-if="!to.inputType || to.inputType == 'checkbox'" type="checkbox" v-model="model[field.key]" :value="option.value || option" @blur="onBlur" @focus="onFocus" @click="onClick" @change="onChange" @keyup="onKeyup" @keydown="onKeydown" v-formly-atts="to.atts" :class="to.classes">
      <input v-if="to.inputType == 'radio'" type="radio" v-model="model[field.key]" :value="option.value || option" @blur="onBlur" @focus="onFocus" @click="onClick" @change="onChange" @keyup="onKeyup" @keydown="onKeydown" v-formly-atts="to.atts" :class="to.classes">
      {{option.label || option}}
    </label>
    <error-display :form="form" :field="field.key"></error-display>
  </div>
</template>

<script>
 import baseField from './baseField';
 export default {
     mixins: [baseField],
     created: function(){
         //set the default value to be an array if it's a checkbox
         let type = this.to.inputType;
         if ( (!type || type == 'checkbox') && this.model[ this.field.key ] == '') this.$set(this.model, this.field.key, []);
     }
 }
</script>
```

i think is as simple as adding
```
...
<label > {{field.templateOptions.label}}</label>
<label v-for="option in field.options" :class="to.labelClasses">
...
```

**Comment by matt-sanders** [comment]
@rodrigoAbril You're right, it looks pretty simple, I'll see if I can get this pushed soon.

**Comment by matt-sanders** [comment]
@rodrigoAbril just pushed version 2.2.7 which includes this label.
