### ISSUE TITLE
Errors Support

### ISSUE THREAD

**Issue by mikeerickson** [formly-js/vue-formly-bootstrap#6]
I see in the docs that `errors` are not yet supported.   Do you have an ETA?  I have to add errors below each form object.

**Comment by matt-sanders** [comment]
Yes, errors are actually supported now. I think I wrote docs somewhere, one sec and I'll find them.

**Comment by matt-sanders** [comment]
https://matt-sanders.gitbooks.io/vue-formly/content/v/2.0/how_to_use/validation.html

**Comment by mikeerickson** [comment]
![image](https://cloud.githubusercontent.com/assets/183153/23675854/94f6c958-032f-11e7-920a-1403b09af1f4.png)

**Comment by mikeerickson** [comment]
OK, I will review your docs regarding error handling

Thanks for your time!

**Comment by matt-sanders** [comment]
No worries, let me know if you have any other troubles.

**Comment by mikeerickson** [comment]
@matt-sanders are you available for a quick chat?  email? or something else?

would like to discuss options for date and time pickers?

codedungeon@gmail if you are available

**Comment by Luddinus** [comment]
How can I set manually the errors?

I get the errors from the server.

According to the template (fieldInput), I have to set the "hasError" property to true, and I have to set some message in order to "error-display" component displays the message.

**Comment by matt-sanders** [comment]
Hey @Luddinus 

I haven't sorted anything for async validation quite yet but you could do it manually. Without testing this I'm thinking you could do something like 
```js
//get the setError function 
import {setError} from 'path_to_vue_formly/util';

function myAsyncValidator(form, key, validatorKey){
   axios.post('/someurl', {})
       .then( function(response){
              setError(form, key, validatorKey, response.valid, response.message);
        });
}
```

That's a very very quick and rough solution but should get you going. Take a look in vue-formly/src/util.js for the `setError` method. Also take a look at vue-formly/src/components/FormlyField.vue for it's implementation. But for a quick explanation `setError` takes five arguments:

`setError(form, key, err, isError, message = false){...}`
`form` is the form object that you pass to the formly-form component. This holds the errors etc
`key` is the key of the field
`err` is the key of the validator
`isError` is a boolean whether there's an error or not
`message` is an optional message to display

Hope that helps!

**Comment by Luddinus** [comment]
Thx @matt-sanders, I'll give a shot

**Comment by matt-sanders** [comment]
@Luddinus I've just released a new version which has support for asynchronous validation and setting the error from the server. Take a look at the updated documentation first as it is a breaking change. Hope it helps!
