### ISSUE TITLE
fieldInput.vue input type is not filled by inputType as advertised

### ISSUE THREAD

**Issue by blalan** [formly-js/vue-formly-bootstrap#9]
In fieldInput.Vue, the input element type attribute is set to "text", shouldn't it be :type="to.inputType"?

**Comment by matt-sanders** [comment]
In Vue 2.x we can no longer bind `:type` and `:model` at the same time so I had set up a directive to set the input type after it was mounted. With the next upcoming release of Vue Formly Bootstrap I'm moving to render functions which will actually make this issue redundant as we have to roll our own `v-model` implementation. This means we can go back to binding to `:type`.
